# Generated by Django 4.2.10 on 2025-06-07 23:32

from django.db import migrations, models
import paint_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_id', models.CharField(db_index=True, default=paint_app.models.generate_drawing_id, help_text='Identificador único para un conjunto de estados de historial de un dibujo.', max_length=100)),
                ('version', models.PositiveIntegerField(db_index=True, help_text='Número de versión secuencial dentro de un drawing_id, representa un paso en el historial.')),
                ('image_data_ppm', models.BinaryField(help_text='Contenido binario del archivo PPM que representa este estado del lienzo.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se guardó este estado.')),
            ],
            options={
                'verbose_name': 'Estado del Lienzo',
                'verbose_name_plural': 'Estados del Lienzo',
                'ordering': ['drawing_id', 'version'],
                'unique_together': {('drawing_id', 'version')},
            },
        ),
    ]
